### ISSUE TITLE
Compiling with newer VS2015

### ISSUE THREAD

**Issue by Positive07** [moteus/librs232#4]
This would be really helpful since the projects is quite outdated and rises some warnings and issues with deprecated functions.

I haven't tried to compile it lately, but VS2015 community version is free so it would be really nice

**Comment by moteus** [comment]
It compile with VS2012 without any problem. I see no reason why it will have some problem with VS2015
This from AppVeyor log
```bash
> luarocks make rockspecs/rs232-scm-0.rockspec
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by Positive07** [comment]
Oh I'm sorry, last time I tried I think I used one of the project solutions and I got a bunch of warnings and whatnot.

How can I easily achieve a manual install, may it be with a project solution or simply command line instructions since I'm not scared of it, instructions would be nice.

What are the bare minimum commands, switchs and declarations I should use?

**Comment by Positive07** [comment]
Closing this since it's irrelevant and this was my mistake
